// Generated by Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import CoreData;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("Mobelisk")
@class TimeStamp;

/// Model class for Acceleration data
SWIFT_CLASS("_TtC8Mobelisk12Acceleration")
@interface Acceleration : NSObject
/// x position of device
@property (nonatomic, readonly) float xPosition;
/// y position of device
@property (nonatomic, readonly) float yPosition;
/// z position of device
@property (nonatomic, readonly) float zPosition;
/// timestamp at which data captured
@property (nonatomic, readonly, strong) TimeStamp * _Nonnull timeStamp;
/// total acceleration data
@property (nonatomic, readonly) float totalAcceleration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end



@class NSError;

/// Accelerometer report.
/// The Accelerometer report provides an interface to get acceleration details. Registering for notification will give updated Acceleration data at defined time.
SWIFT_CLASS("_TtC8Mobelisk19AccelerometerReport")
@interface AccelerometerReport : NSObject
/// Default initializer.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Set the polling rate at which acceleration updates will be provided from case.
/// <em>-registerForNotification(atTimeInterval:completionHandler:)</em> should be called in order to receive Acceleration Data.
/// \param pollingRate Polling rate at which acceleration update will be sent
///
/// \param completionHandler <em>@escaping</em> completionHandler which will return error if occurred else nil.
///
- (void)setAccelerometerMeterPollingRate:(float)pollingRate completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Returns the current acceleration polling rate.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the polling rate.
///
- (void)getAccelerometerMeterPollingRateWithCompletionHandler:(void (^ _Nonnull)(float, NSError * _Nullable))completionHandler;
/// Interface definition for a callback to be invoked when a Acceleration data is received.
/// \param atTimeInterval Time interval at which acceleration data needed
///
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the acceleration data.
///
+ (void)registerForNotificationWithIdentifier:(NSString * _Nonnull)identifier atTimeInterval:(NSTimeInterval)duration completionHandler:(void (^ _Nonnull)(Acceleration * _Nonnull))completionHandler;
/// Interface definition to de-register for acceleration notifications.
+ (void)deRegisterForNotificationWithIdentifier:(NSString * _Nonnull)identifier;
@end

/// Action Button number enum.
/// The ButtonNumber enum is used to identify buttons when receiving key press events from the Enterprise Appliance Basecase.
/// Action Buttons are numbered starting from 0.
/// In most cases the ACTION LED number ‘ActionLedNumber’ will correspond to the ‘ActionButtonNumber’ ACTION BUTTON number.
typedef SWIFT_ENUM(NSInteger, ActionButtonNumber) {
/// Action Button 0.
  ActionButtonNumberButton0 = 0,
/// Action Button 1.
  ActionButtonNumberButton1 = 1,
/// Action Button Unknown.
  ActionButtonNumberUnknown = 2,
};


/// Action Button press report.
/// This report is sent on key up and key down to indicate that a state of a physical button on the Enterprise Appliance changed.
SWIFT_CLASS("_TtC8Mobelisk23ActionButtonStateReport")
@interface ActionButtonStateReport : NSObject
/// Action Button number pressed.
@property (nonatomic) enum ActionButtonNumber buttonNumber;
/// Action Button press state.
@property (nonatomic) BOOL isButtonDown;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

/// Action LED number enum.
/// The LedNumber enum is used to address LEDs when sending commands to turn on or off LEDs on the Enterprise Appliance Basecase.
/// LEDs are numbered starting from 0.
/// In most cases the LED number ‘ActionLedNumber’ will correspond to the ‘ButtonNumber’ button number.
typedef SWIFT_ENUM(NSInteger, ActionLedNumber) {
/// Action LED 0
  ActionLedNumberLED_0 = 0,
/// Action LED 1
  ActionLedNumberLED_1 = 1,
};


/// Model class for Barcode data
SWIFT_CLASS("_TtC8Mobelisk7Barcode")
@interface Barcode : NSObject
/// barcode
@property (nonatomic, readonly, copy) NSString * _Nonnull barcode;
/// timeStamp
@property (nonatomic, readonly, strong) TimeStamp * _Nonnull timeStamp;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

enum PowerCondition : uint8_t;
enum ScanMode : NSInteger;

/// BarcodeScan report.
/// The BarcodeScan report provides an interface to get barcode details.
SWIFT_CLASS("_TtC8Mobelisk17BarcodeScanReport")
@interface BarcodeScanReport : NSObject
/// Default initializer.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Turn on/off Barcode scanner.
/// \param completionHandler <em>@escaping</em> completionHandler which will return error if occurred else nil.
///
- (void)setBarcodeScannerStatus:(enum PowerCondition)status completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Return Barcode scanner status - on/off.
/// <ul>
///   <li>
///     parameters:
///   </li>
///   <li>
///     completionHandler: <em>@escaping</em> completionHandler which will return - state.
///   </li>
/// </ul>
- (void)getBarcodeScannerStatusWithCompletionHandler:(void (^ _Nonnull)(enum PowerCondition, NSError * _Nullable))completionHandler;
/// Starts scanning for barcode.
/// <em>-registerForBarcodeScanNotification(completionHandler:)</em> should be called in order to receive Barcode data.
/// <ul>
///   <li>
///     parameters:
///   </li>
///   <li>
///     completionHandler: <em>@escaping</em> completionHandler which will return error if occurred else nil.
///   </li>
/// </ul>
- (void)startScanWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Set scan mode as Serial or HID.
/// <ul>
///   <li>
///     parameters:
///   </li>
///   <li>
///     scanMode: Provide scan mode Serial or HID. Default is HID.
///   </li>
/// </ul>
+ (void)setScanMode:(enum ScanMode)scanMode;
/// Stops scanning for barcode.
/// <em>-registerForBarcodeScanNotification(completionHandler:)</em> should be called in order to receive Barcode data.
/// <ul>
///   <li>
///     parameters:
///   </li>
///   <li>
///     completionHandler: <em>@escaping</em> completionHandler which will return error if occurred else nil.
///   </li>
/// </ul>
- (void)stopScanWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Interface definition for a callback to be invoked when a Barcode data is received.
/// <ul>
///   <li>
///     parameters:
///   </li>
///   <li>
///     completionHandler: <em>@escaping</em> completionHandler which will return - the barcode data.
///   </li>
/// </ul>
+ (void)registerForBarcodeScanNotificationWithIdentifier:(NSString * _Nonnull)identifier completionHandler:(void (^ _Nonnull)(Barcode * _Nonnull))completionHandler;
/// Interface definition to de-register for barcode notifications.
+ (void)deRegisterForNotificationWithIdentifier:(NSString * _Nonnull)identifier;
@end



enum ChargerStatus : NSInteger;
enum CaseChargingStatus : NSInteger;
enum DeviceChargingStatus : NSInteger;

/// Model class for Smartcase battery information
SWIFT_CLASS("_TtC8Mobelisk11BatteryInfo")
@interface BatteryInfo : NSObject
/// percentage
@property (nonatomic, readonly) NSInteger percentage;
/// fraction
@property (nonatomic, readonly) NSInteger fraction;
/// chargerStatus
@property (nonatomic, readonly) enum ChargerStatus chargerStatus;
/// caseChargingStatus
@property (nonatomic, readonly) enum CaseChargingStatus caseChargingStatus;
/// deviceChargingStatus
@property (nonatomic, readonly) enum DeviceChargingStatus deviceChargingStatus;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

/// Button number enum.
/// The ButtonNumber enum is used to identify buttons when receiving key press events from the Enterprise Appliance Endcap.
/// Buttons are numbered starting from 0.
/// In most cases the LED number ‘LedNumber’ will correspond to the ‘ButtonNumber’ button number.
typedef SWIFT_ENUM(NSInteger, ButtonNumber) {
/// Enterprise Appliance Button 0.
  ButtonNumberButton0 = 0,
/// Enterprise Appliance Button 1.
  ButtonNumberButton1 = 1,
/// Enterprise Appliance Button Unknown.
  ButtonNumberUnknown = 2,
};


/// Button press report.
/// This report is sent on key up and key down to indicate that a state of a physical button on the Enterprise Appliance changed.
SWIFT_CLASS("_TtC8Mobelisk17ButtonStateReport")
@interface ButtonStateReport : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

/// Enum for Smartcase’s Charging Status
typedef SWIFT_ENUM(NSInteger, CaseChargingStatus) {
/// notCharging
  CaseChargingStatusNotCharging = 0,
/// charging
  CaseChargingStatusCharging = 1,
/// chargingError
  CaseChargingStatusChargingError = 2,
};

/// Enum for Smartcase Charger Status
typedef SWIFT_ENUM(NSInteger, ChargerStatus) {
/// notCharging
  ChargerStatusNotCharging = 0,
/// chargingFromACPlug
  ChargerStatusChargingFromACPlug = 1,
/// chargingFromUSB
  ChargerStatusChargingFromUSB = 2,
/// qiCharging
  ChargerStatusQiCharging = 4,
};



/// Enum for Device’s Charging status
typedef SWIFT_ENUM(NSInteger, DeviceChargingStatus) {
/// notCharging
  DeviceChargingStatusNotCharging = 0,
/// charging
  DeviceChargingStatusCharging = 1,
};


/// EAConfigInfo object gives the configuration data, and includes USB VID/PID, GPIO input/output direction, GPIO port numbers, input polarity, output default levels, and GPIO enabled/disabled status.
SWIFT_CLASS("_TtC8Mobelisk12EAConfigInfo")
@interface EAConfigInfo : NSObject
@property (nonatomic, readonly) NSInteger portNumbersGPIO0And1;
@property (nonatomic, readonly) NSInteger portNumbersGPIO2And3;
@property (nonatomic, readonly) NSInteger portNumbersGPIO4And5;
@property (nonatomic, readonly) NSInteger portNumbersGPIO6And7;
@property (nonatomic, readonly) NSInteger portNumbersGPIO8And9;
@property (nonatomic, readonly) NSInteger portNumbersGPIO10And11;
@property (nonatomic, readonly) NSInteger portNumbersGPIO12And13;
@property (nonatomic, readonly) NSInteger portNumbersGPIO14And15;
@property (nonatomic, readonly) NSInteger portNumbersGPIO16And17;
@property (nonatomic, readonly) NSInteger portNumbersGPIO18And19;
@property (nonatomic, readonly) NSInteger directionGPIO0To7;
@property (nonatomic, readonly) NSInteger directionGPIO8To15;
@property (nonatomic, readonly) NSInteger directionGPIO16To19;
@property (nonatomic, readonly) NSInteger inputPolarityOrOutputDefaultGPIO0To7;
@property (nonatomic, readonly) NSInteger inputPolarityOrOutputDefaultGPIO8To15;
@property (nonatomic, readonly) NSInteger inputPolarityOrOutputDefaultGPIO16To19;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, EndCapNumber) {
  EndCapNumberBaseCase = 0,
  EndCapNumberOne = 1,
  EndCapNumberTwo = 2,
};


/// EndCapStatus provides the status of connected endcaps.
SWIFT_CLASS("_TtC8Mobelisk12EndCapStatus")
@interface EndCapStatus : NSObject
/// Provides the status of end cap A.
@property (nonatomic, readonly) enum PowerCondition endCapAStatus;
/// Provides the status of end cap B.
@property (nonatomic, readonly) enum PowerCondition endCapBStatus;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

enum LedNumber : NSInteger;
@class GetGPIOStatesInfo;
@class UIColor;
@class Pattern;
@class GetGPIOFlashPatternInfo;
@class GetGPIOPWMInfo;

/// The main EnterpriseApplianceAPI class is a high-level interface used to control all parameters (on/off,
/// color, brightness and flash patterns) of the illuminated buttons as well as request device state reports.
SWIFT_CLASS("_TtC8Mobelisk22EnterpriseApplianceAPI")
@interface EnterpriseApplianceAPI : NSObject
/// Initializer for EnterpriseApplianceAPI
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Get EA Configuration.
/// \param completionHandler call back function which contains EAConfigInfo object and error object for success or failure. EAConfigInfo object gives the configuration data, and includes USB VID/PID, GPIO input/output direction, GPIO port numbers, input polarity, output default levels, and GPIO enabled/disabled status.
///
- (void)getEAConfigWithCompletionHandler:(void (^ _Nonnull)(EAConfigInfo * _Nullable, NSError * _Nullable))completionHandler;
/// Power on LED.
/// \param ledNumber the Led Number.
///
/// \param completionHandler call back function for success or failure.
///
- (void)powerOnLedWithLedNumber:(enum LedNumber)ledNumber completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Get the state of the GPIOs, including both inputs and outputs.
/// \param completionHandler call back function which contains GetGPIOStatesInfo object and error object for success or failure. GetGPIOStatesInfo object gives the state of the GPIOs, including both inputs and outputs.
///
- (void)getGPIOStatesWithCompletionHandler:(void (^ _Nonnull)(GetGPIOStatesInfo * _Nullable, NSError * _Nullable))completionHandler;
/// Power on LED, set the color of illumination and set the flash pattern.
/// \param ledNumber the Led Number.
///
/// \param color color that you want to apply for Led.
///
/// \param pattern flash pattern to set.
///
/// \param brightness brightness to apply to RGB components. It must be within 0 to 255.
///
/// \param completionHandler call back function for success or failure.
///
- (void)powerOnLedWithLedNumber:(enum LedNumber)ledNumber color:(UIColor * _Nonnull)color brightness:(NSInteger)brightness pattern:(Pattern * _Nonnull)pattern completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Power on LED, set the color, brightness of illumination and set the flash pattern.
/// \param ledNumber the Led Number.
///
/// \param color color that you want to apply for Led.
///
/// \param pattern flash pattern to set.
///
/// \param completionHandler call back function for success or failure.
///
- (void)powerOnLedWithLedNumber:(enum LedNumber)ledNumber color:(UIColor * _Nonnull)color pattern:(Pattern * _Nonnull)pattern completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Power off Led.
/// \param ledNumber the Led Number.
///
/// \param completionHandler call back function for success or failure.
///
- (void)powerOffLedWithLedNumber:(enum LedNumber)ledNumber completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)setPatternForLedNumber:(enum LedNumber)ledNumber pattern:(Pattern * _Nonnull)pattern completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Get flash pattern for GPIONumber.
/// \param completionHandler call back function which contains GetGPIOFlashPatternInfo object and error object for success or failure. GetGPIOFlashPatternInfo object gives current flash pattern for GPIONumber.
///
- (void)getGPIOFlashPatternForGPIONumber:(NSInteger)number completionHandler:(void (^ _Nonnull)(GetGPIOFlashPatternInfo * _Nullable, NSError * _Nullable))completionHandler;
/// This method is used to set the Led color.
/// \param ledNumber Led Number for which to set the color.
///
/// \param color color that you want to apply for Led.
///
/// \param completionHandler call back function for success or failure.
///
- (void)setColorForLedNumber:(enum LedNumber)ledNumber color:(UIColor * _Nonnull)color completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// This method is used to set the Led color.
/// \param ledNumber Led Number for which to set the color.
///
/// \param color color that you want to apply for Led.
///
/// \param brightness brightness to apply to RGB components. It must be within 0 to 255.
///
/// \param completionHandler call back function for success or failure.
///
- (void)setColorForLedNumber:(enum LedNumber)ledNumber color:(UIColor * _Nonnull)color brightness:(NSInteger)brightness completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Get current PWM duty cycle of the output GPIOs.
/// \param completionHandler call back function which contains GetGPIOPWMInfo object and error object for
/// success or failure. GetGPIOPWMInfo object gives current PWM duty cycle of the output GPIOs.
///
- (void)getGPIOPWMWithCompletionHandler:(void (^ _Nonnull)(GetGPIOPWMInfo * _Nullable, NSError * _Nullable))completionHandler;
/// Power on Action LED.
/// \param actionLedNumber Action Led Number.
///
/// \param completionHandler call back function for success or failure.
///
- (void)setActionButtonLedOnActionLedNumber:(enum ActionLedNumber)actionLedNumber completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Power off Action LED.
/// \param actionLedNumber Action Led Number.
///
/// \param completionHandler call back function for success or failure.
///
- (void)setActionButtonLedOffWithActionLedNumber:(enum ActionLedNumber)actionLedNumber completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
@end


/// Model class for Environment data
SWIFT_CLASS("_TtC8Mobelisk11Environment")
@interface Environment : NSObject
/// Temperature
@property (nonatomic, readonly) float temperature;
/// Humidity
@property (nonatomic, readonly) float humidity;
/// Barometric Pressure
@property (nonatomic, readonly) float barometricPressure;
/// TimeStamp
@property (nonatomic, readonly, strong) TimeStamp * _Nonnull timeStamp;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


/// Environment report.
/// The environment report provides an interface to get environment details. Registering for notification will give updated Environment data at defined time.
SWIFT_CLASS("_TtC8Mobelisk17EnvironmentReport")
@interface EnvironmentReport : NSObject
/// Default initializer.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Set the polling rate at which environment updates will be provided from case.
/// <em>-registerForNotification(atTimeInterval:completionHandler:)</em> should be called in order to receive Environment Data.
/// \param pollingRate Polling rate at which environment update will be sent
///
/// \param completionHandler <em>@escaping</em> completionHandler which will return error if occurred else nil.
///
- (void)setEnvironmentalPollingRate:(float)pollingRate completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Returns the current environment polling rate.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the polling rate.
///
- (void)getEnvironmentalPollingRateWithCompletionHandler:(void (^ _Nonnull)(float, NSError * _Nullable))completionHandler;
/// Returns the current environment details.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the Environment data.
///
- (void)getEnvironmentalDetailsWithCompletionHandler:(void (^ _Nonnull)(Environment * _Nullable, NSError * _Nullable))completionHandler;
/// Interface definition for a callback to be invoked when a Environment data is received.
/// \param atTimeInterval Time interval at which environment data needed
///
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the environment data.
///
+ (void)registerForNotificationWithIdentifier:(NSString * _Nonnull)identifier atTimeInterval:(NSTimeInterval)duration completionHandler:(void (^ _Nonnull)(Environment * _Nonnull))completionHandler;
/// Interface definition to de-register for environment notifications.
+ (void)deRegisterForNotificationWithIdentifier:(NSString * _Nonnull)identifier;
@end

/// Enum for Sensor’s Functional States
typedef SWIFT_ENUM(uint8_t, FunctionalState) {
/// unknown
  FunctionalStateUnknown = 0b00000000,
/// ok
  FunctionalStateOk = 0b01000000,
/// error
  FunctionalStateError = 0b10000000,
};


/// GetGPIOFlashPatternInfo object gives current flash pattern for GPIONumber.
SWIFT_CLASS("_TtC8Mobelisk23GetGPIOFlashPatternInfo")
@interface GetGPIOFlashPatternInfo : NSObject
@property (nonatomic, readonly) NSInteger number;
@property (nonatomic, readonly) float longFlashOnTime;
@property (nonatomic, readonly) float longFlashOffTime;
@property (nonatomic, readonly) NSInteger longFlashRepetitions;
@property (nonatomic, readonly) float shortFlashOnTime;
@property (nonatomic, readonly) float shortFlashOffTime;
@property (nonatomic, readonly) NSInteger shortFlashRepetitions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


/// GetGPIOPWMInfo object gives current PWM duty cycle of the output GPIOs.
SWIFT_CLASS("_TtC8Mobelisk14GetGPIOPWMInfo")
@interface GetGPIOPWMInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


/// GetGPIOStatesInfo object gives the state of the GPIOs, including both inputs and outputs.
SWIFT_CLASS("_TtC8Mobelisk17GetGPIOStatesInfo")
@interface GetGPIOStatesInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

/// LED number enum.
/// The LedNumber enum is used to address LEDs when sending commands to illuminate or set color on the Enterprise Appliance Endcap.
/// LEDs are numbered starting from 0.
typedef SWIFT_ENUM(NSInteger, LedNumber) {
/// Enterprise Appliance LED 0
  LedNumberLED_0 = 0,
/// Enterprise Appliance LED 1
  LedNumberLED_1 = 1,
};

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS("_TtC8Mobelisk11MODailySync")
@interface MODailySync : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface MODailySync (SWIFT_EXTENSION(Mobelisk))
@property (nonatomic, copy) NSDate * _Nullable barcode;
@property (nonatomic, copy) NSDate * _Nullable barometricPressure;
@property (nonatomic, copy) NSDate * _Nullable distanceTravelled;
@property (nonatomic, copy) NSDate * _Nullable heatIndex;
@property (nonatomic, copy) NSString * _Nullable serialNumber;
@property (nonatomic, copy) NSDate * _Nullable workingEnvironement;
@end


SWIFT_CLASS("_TtC8Mobelisk20MPOSCardReadResponse")
@interface MPOSCardReadResponse : NSObject
@property (nonatomic) BOOL isCardReadSuccessful;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, MPOSDeviceConnection) {
/// MPOSDevice disconnected.
  MPOSDeviceConnectionDisconnected = 0,
/// MPOSDevice connected.
  MPOSDeviceConnectionConnected = 1,
};


SWIFT_CLASS("_TtC8Mobelisk27MPOSDeviceConnectionDetails")
@interface MPOSDeviceConnectionDetails : NSObject
/// MPOSDevice Connection Status
@property (nonatomic, readonly) enum MPOSDeviceConnection connectionStatus;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end




/// MPOS report.
/// The MPOSReport provides an interface to get MPOS details.
SWIFT_CLASS("_TtC8Mobelisk10MPOSReport")
@interface MPOSReport : NSObject
/// Default initializer.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Turn on/off MPOS.
/// \param completionHandler <em>@escaping</em> completionHandler which will return error if occurred else nil.
///
- (void)setMPOSStatus:(enum PowerCondition)status completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Return MPOS status - on/off.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - state.
///
- (void)getMPOSStatusWithCompletionHandler:(void (^ _Nonnull)(enum PowerCondition, NSError * _Nullable))completionHandler;
@end


SWIFT_CLASS("_TtC8Mobelisk10MPOSRouter")
@interface MPOSRouter : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MPOSRouter * _Nonnull shared;)
+ (MPOSRouter * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (void)sendDataToEndCapWithData:(NSData * _Nonnull)data completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
@end


/// Configuration class.
/// It provides configuration to the Mobelisk framework about how it should build.
/// It has two properties:
/// <ul>
///   <li>
///     isCoreApp - Is indicate whether framework is build from Core app.
///   </li>
///   <li>
///     appGroupIdentifier - This is app group indentifier generated from developers account.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC8Mobelisk14MobeliskConfig")
@interface MobeliskConfig : NSObject
/// Default intialiser with core app indicator and app group identifier.
- (nonnull instancetype)initWithIsCoreApp:(BOOL)isCoreApp appGroupIdentifier:(NSString * _Nonnull)appGroupIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class MPOSBypassManager;

/// Mobelisk frameworks manager class.
/// It provides an interface to build the framework with MobeliskConfig model.
/// It also provides an interface for push notification helper methods.
SWIFT_CLASS("_TtC8Mobelisk15MobeliskManager")
@interface MobeliskManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) MPOSBypassManager * _Nullable mPOSBypassManager;)
+ (MPOSBypassManager * _Nullable)mPOSBypassManager SWIFT_WARN_UNUSED_RESULT;
+ (void)setMPOSBypassManager:(MPOSBypassManager * _Nullable)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
/// Build the framework with MobeliskConfig model.
+ (void)buildWithConfiguration:(MobeliskConfig * _Nonnull)config;
@end


@interface MobeliskManager (SWIFT_EXTENSION(Mobelisk))
/// Setup APNS token to receive push notifications intended for Mobelisk framework.
+ (void)setAPNSTokenWithToken:(NSString * _Nonnull)token;
/// Handle received push notification.
+ (void)validatePushNotificationWithUserInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo;
@end


















/// Flash Pattern.
/// The flash pattern consists of a number of long flashes and short flashes, which can be set in
/// increments of 100ms, from 0 to 25.5 seconds.
/// The number of long and short flashes can be set from 0 to 128.
/// The LED will illuminate for the on and off durations of the long patterns, for the long pattern
/// repetition number (or skip it if this number is 0). When finished, it will start illuminating for the
/// on and off durations of the short patterns, for the short pattern repetition number (or skip it if this
/// number is 0). It then repeats and begins with the long pattern again.
SWIFT_CLASS("_TtC8Mobelisk7Pattern")
@interface Pattern : NSObject
/// SOLID illumination pattern.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Pattern * _Nonnull SOLID;)
+ (Pattern * _Nonnull)SOLID SWIFT_WARN_UNUSED_RESULT;
/// BLINK_SLOW illumination pattern (blink once per second).
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Pattern * _Nonnull BLINK_SLOW;)
+ (Pattern * _Nonnull)BLINK_SLOW SWIFT_WARN_UNUSED_RESULT;
/// BLINK_FAST illumination pattern (blink twice per second).
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Pattern * _Nonnull BLINK_FAST;)
+ (Pattern * _Nonnull)BLINK_FAST SWIFT_WARN_UNUSED_RESULT;
/// BLINK_LONG_SHORT illumination pattern (one long, one short).
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Pattern * _Nonnull BLINK_LONG_SHORT;)
+ (Pattern * _Nonnull)BLINK_LONG_SHORT SWIFT_WARN_UNUSED_RESULT;
/// Minimum flash time in seconds.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) float MIN_FLASH_TIME;)
+ (float)MIN_FLASH_TIME SWIFT_WARN_UNUSED_RESULT;
/// Maximum flash time in seconds.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) float MAX_FLASH_TIME;)
+ (float)MAX_FLASH_TIME SWIFT_WARN_UNUSED_RESULT;
/// Minimum repetitions.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger MIN_REPETITIONS;)
+ (NSInteger)MIN_REPETITIONS SWIFT_WARN_UNUSED_RESULT;
/// Maximum repetitions.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger MAX_REPETITIONS;)
+ (NSInteger)MAX_REPETITIONS SWIFT_WARN_UNUSED_RESULT;
/// the long flash on time.
@property (nonatomic) float longFlashOnTime;
/// the long flash off time.
@property (nonatomic) float longFlashOffTime;
/// the long flash repetitions.
@property (nonatomic) NSInteger longFlashRepetitions;
/// the short flash on time.
@property (nonatomic) float shortFlashOnTime;
/// the short flash off time.
@property (nonatomic) float shortFlashOffTime;
/// the short flash repetitions.
@property (nonatomic) NSInteger shortFlashRepetitions;
/// Instantiates a new Pattern.
/// \param longFlashOnTime the long flash on time.
///
/// \param longFlashOffTime the long flash off time.
///
/// \param longFlashRepetitions the long flash repetitions.
///
/// \param shortFlashOnTime the short flash on time.
///
/// \param shortFlashOffTime the short flash off time.
///
/// \param shortFlashRepetitions the short flash repetitions.
///
- (nonnull instancetype)initWithLongFlashOnTime:(float)longFlashOnTime longFlashOffTime:(float)longFlashOffTime longFlashRepetitions:(NSInteger)longFlashRepetitions shortFlashOnTime:(float)shortFlashOnTime shortFlashOffTime:(float)shortFlashOffTime shortFlashRepetitions:(NSInteger)shortFlashRepetitions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(uint8_t, PowerCondition) {
  PowerConditionOff = 0,
  PowerConditionOn = 1,
  PowerConditionDoNotChange = 2,
  PowerConditionTurnOffWhenTabletSleep = 3,
  PowerConditionTurnOffWhenTabletSleepAndBatteryPower = 4,
  PowerConditionTurnOffWhenTabletSleepAndACPower = 5,
};


SWIFT_CLASS("_TtC8Mobelisk19SafeDriverDataModel")
@interface SafeDriverDataModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// ScanMode enum.
typedef SWIFT_ENUM(NSInteger, ScanMode) {
/// ScanMode - HID.
  ScanModeHid = 0,
/// ScanMode - Serial.
  ScanModeSerial = 1,
};

enum SensorStatus : uint8_t;

/// Model class for Sensor
SWIFT_CLASS("_TtC8Mobelisk6Sensor")
@interface Sensor : NSObject
/// id
@property (nonatomic, readonly) NSInteger id;
/// state
@property (nonatomic, readonly) enum FunctionalState state;
/// status
@property (nonatomic, readonly) enum SensorStatus status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, SensorIdentifier) {
  SensorIdentifierNone = 0,
  SensorIdentifierMagtekMSR = 16,
  SensorIdentifierIntermecBCS = 32,
  SensorIdentifierZebraBCS = 33,
  SensorIdentifierChimeraEA = 49,
  SensorIdentifierMinismartII = 64,
  SensorIdentifierIdTech4880 = 80,
  SensorIdentifierRfidReader = 96,
  SensorIdentifierEnvironmentSensor = -1,
  SensorIdentifierShockSensor = -2,
  SensorIdentifierPositionSensor = -3,
  SensorIdentifierEnterpriseAppliance = -4,
  SensorIdentifierSafeDriver = -5,
};

/// Enum for Sensor’s Status
typedef SWIFT_ENUM(uint8_t, SensorStatus) {
/// idle
  SensorStatusIdle = 0b00000000,
/// busy
  SensorStatusBusy = 0b00000001,
/// initializing
  SensorStatusInitializing = 0b00000010,
/// off
  SensorStatusOff = 0b00000011,
/// sleep
  SensorStatusSleep = 0b00000100,
/// unknown
  SensorStatusUnknown = 5,
};


/// Model class for Shock data
SWIFT_CLASS("_TtC8Mobelisk9ShockData")
@interface ShockData : NSObject
/// x Value
@property (nonatomic, readonly) float xValue;
/// y Value
@property (nonatomic, readonly) float yValue;
/// z Value
@property (nonatomic, readonly) float zValue;
/// magnitude
@property (nonatomic, readonly) float magnitude;
/// total
@property (nonatomic, readonly) float total;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


/// Model class for Shock event
SWIFT_CLASS("_TtC8Mobelisk10ShockEvent")
@interface ShockEvent : NSObject
/// samplingRate
@property (nonatomic, readonly) float samplingRate;
/// fallTime
@property (nonatomic, readonly) float fallTime;
/// Array of ShockData model
@property (nonatomic, readonly, copy) NSArray<ShockData *> * _Nonnull shocks;
/// timeStamp
@property (nonatomic, readonly, strong) TimeStamp * _Nonnull timeStamp;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


/// Model class for Shock event config
SWIFT_CLASS("_TtC8Mobelisk16ShockEventConfig")
@interface ShockEventConfig : NSObject
/// isEnabled
@property (nonatomic, readonly) BOOL isEnabled;
/// magnitude
@property (nonatomic, readonly) float magnitude;
/// fallTime
@property (nonatomic, readonly) NSInteger fallTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


/// Shock event report.
/// The Shock event report provides an interface to get shock alert with specified magnitude and fall time.
SWIFT_CLASS("_TtC8Mobelisk16ShockEventReport")
@interface ShockEventReport : NSObject
/// Default initializer.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Set the shock alert condition at which shock events will be provided from case.
/// -registerForNotification(completionHandler:) should be called in order to receive Shock events.
/// \param isEnabled Enable/Disable shock alert events delivery
///
/// \param magnitude Magnitude of shock
///
/// \param completionHandler <em>@escaping</em> completionHandler which will return error if occurred else nil.
///
- (void)setShockAlertConditionWithIsEnabled:(BOOL)isEnabled magnitude:(float)magnitude fallTime:(NSInteger)fallTime completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Returns the shock alert condition.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the ShockEventConfig model.
///
- (void)getShockAlertConditionWithCompletionHandler:(void (^ _Nonnull)(ShockEventConfig * _Nullable, NSError * _Nullable))completionHandler;
/// Interface definition for a callback to be invoked when a Shock event is received.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the shock event data.
///
+ (void)registerForNotificationWithIdentifier:(NSString * _Nonnull)identifier completionHandler:(void (^ _Nonnull)(ShockEvent * _Nonnull))completionHandler;
/// Interface definition to de-register for shock alert notifications.
+ (void)deRegisterForNotificationWithIdentifier:(NSString * _Nonnull)identifier;
@end


/// Model class for Smartcase information
SWIFT_CLASS("_TtC8Mobelisk16SmartCaseDetails")
@interface SmartCaseDetails : NSObject
/// batteryStatus
@property (nonatomic, readonly, copy) NSString * _Nonnull batteryStatus;
/// firmwareVersionNumber
@property (nonatomic, readonly, copy) NSString * _Nonnull firmwareVersionNumber;
/// serialNumber
@property (nonatomic, readonly, copy) NSString * _Nonnull serialNumber;
/// isActive
@property (nonatomic, readonly) BOOL isActive;
/// hasIssue
@property (nonatomic, readonly) BOOL hasIssue;
/// id
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
/// type
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
/// modelNumber
@property (nonatomic, readonly, copy) NSString * _Nonnull modelNumber;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class SmartCaseSensor;

@interface SmartCaseDetails (SWIFT_EXTENSION(Mobelisk))
- (NSArray<SmartCaseSensor *> * _Nonnull)listOfConnectedSensors SWIFT_WARN_UNUSED_RESULT;
@end


/// Smart case report.
/// The smart case report contains all relevant hardware version information needed to identify a case.
SWIFT_CLASS("_TtC8Mobelisk15SmartCaseReport")
@interface SmartCaseReport : NSObject
/// Default initializer.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Returns the case battery details.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the BatteryInfo model with expected data.
///
- (void)getSmartCaseBatteryDetailsWithCompletionHandler:(void (^ _Nonnull)(BatteryInfo * _Nullable, NSError * _Nullable))completionHandler;
/// Returns the list of connected sensors.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the list of connected sensors - array of Sensor model.
///
- (void)getListOfSensorsWithCompletionHandler:(void (^ _Nonnull)(NSArray<Sensor *> * _Nullable, NSError * _Nullable))completionHandler;
/// Returns the Part number of Endcap #1.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the part number of Endcap #1.
///
- (void)getEndcapOnePartNumberWithCompletionHandler:(void (^ _Nonnull)(NSInteger, NSError * _Nullable))completionHandler;
/// Returns the Revision of Endcap #1.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the revision of Endcap #1.
///
- (void)getEndcapOneRevisionWithCompletionHandler:(void (^ _Nonnull)(NSInteger, NSError * _Nullable))completionHandler;
/// Returns the Part number of Endcap #2.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the part number of Endcap #2.
///
- (void)getEndcapTwoPartNumberWithCompletionHandler:(void (^ _Nonnull)(NSInteger, NSError * _Nullable))completionHandler;
/// Returns the Revision of Endcap #2.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the revision of Endcap #2.
///
- (void)getEndcapTwoRevisionWithCompletionHandler:(void (^ _Nonnull)(NSInteger, NSError * _Nullable))completionHandler;
/// Interface definition for a callback to be invoked when a Battery status changes.
/// \param completionHandler <em>@escaping</em> completionHandler which will return - the BatteryInfo model.
///
+ (void)registerForBatteryStatusNotificationWithIdentifier:(NSString * _Nonnull)identifier completionHandler:(void (^ _Nonnull)(BatteryInfo * _Nonnull))completionHandler;
/// Interface definition to de-register for battery status notifications.
+ (void)deRegisterForBatteryStatusNotificationWithIdentifier:(NSString * _Nonnull)identifier;
@end


SWIFT_CLASS("_TtC8Mobelisk15SmartCaseSensor")
@interface SmartCaseSensor : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull firmwareVersion;
@property (nonatomic, readonly) enum SensorIdentifier sensorType;
@property (nonatomic, readonly) enum PowerCondition powerState;
@property (nonatomic, readonly) enum EndCapNumber connectedToEndcapNumber;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


/// Model class for TimeStamp
SWIFT_CLASS("_TtC8Mobelisk9TimeStamp")
@interface TimeStamp : NSObject
/// milliSecond
@property (nonatomic, readonly) NSInteger milliSecond;
/// second
@property (nonatomic, readonly) NSInteger second;
/// minute
@property (nonatomic, readonly) NSInteger minute;
/// hour
@property (nonatomic, readonly) NSInteger hour;
/// day
@property (nonatomic, readonly) NSInteger day;
/// month
@property (nonatomic, readonly) NSInteger month;
/// year
@property (nonatomic, readonly) NSInteger year;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface TimeStamp (SWIFT_EXTENSION(Mobelisk))
@property (nonatomic, readonly, copy) NSDate * _Nonnull date;
@end

























SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
